#!/bin/bash
# tary, 2018-10-19 10:54

# BBB
#version=EIA0
year="`date +%Y`"
week="`date +%2W`"
#eepid=`cat bar_code.tmp`
eepid=$1

if [ ${#eepid} -eq 18 ]; then
    echo "Model is: BeagleBone Black Industry"
    version=EIA0
    serial_bar=${eepid:6}
    serial=${year:2:2}${week}SBI${serial_bar:7:5}
    echo "102110423" > sku
    echo "Serial write to EEPROM is: "$serial
fi

if [ ${#eepid} -eq 17 ]; then
    echo "Model is: BeagleBone Black"
    version=00C0
    serial_bar=${eepid:5}
    serial=${year:2:2}${week}SBB${serial_bar:7:5}
    echo "102110420" > sku
    echo "Serial write to EEPROM is: "$serial
fi

config=$(date +%s)
python eeprom_rw.py $version $serial $config; r=$?

echo $serial

leds all off

echo -ne "$eepid" > bar_code.tmp

if [ "$r" -eq 0 ]; then
    echo "========== OK[EEPROM] ========"
    exit 0
else
    echo "========== FAIL[EEPROM] ========"
    exit 1
fi

